---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-postgres-pv
  labels:
    infra-pvname: infra-postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/infra/postgres
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: infra-postgres-pvc
  namespace: agentweb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: infra-postgres-pv
  storageClassName: ""