apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  namespace: agentweb
  name: postgres-svc
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
  type: NodePort